server:
  port: ${PORT:8090}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers

# JWT Configuration (SAME SECRET AS USER SERVICE)
jwt:
  secret: mySecretKeyForJWTTokenGenerationAndValidationThatIsAtLeast512BitsLongToMeetHS512AlgorithmRequirementsForSecureTokenSigning # Same as your User Service
  expiration: 86400000 # 24 hours

# Service URLs
user:
  service:
    url: https://userservice-337812374841.us-central1.run.app

product:
  service:
    url: http://localhost:8081

order:
  service:
    url: https://orderservice-337812374841.us-central1.run.app

supplier:
  service:
    url: http://localhost:8082

inventory:
  service:
    url: http://localhost:8085

resource:
  service:
    url: http://localhost:8086

# Logging
logging:
  level:
    com.ApiGateway.ApiGateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
