server:
  port: ${PORT:8090}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders:
              - Authorization
              - Content-Type
              - X-Gateway
              - X-User-Id
              - X-Username
              - X-User-Roles
            maxAge: 3600
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers
      httpclient:
        connect-timeout: 30000 # 30 seconds
        response-timeout: 90s # 90 seconds for slow Choreo responses
        pool:
          max-connections: 100
          max-idle-time: 60s

# JWT Configuration (SAME SECRET AS USER SERVICE)
jwt:
  secret: mySecretKeyForJWTTokenGenerationAndValidationThatIsAtLeast512BitsLongToMeetHS512AlgorithmRequirementsForSecureTokenSigning # Same as your User Service
  expiration: 86400000 # 24 hours

# Service URLs
user:
  service:
    url: https://userservice-337812374841.us-central1.run.app

product:
  service:
    url: https://d201c53c-c644-4920-ab04-ef977962e680-dev.e1-us-east-azure.choreoapis.dev/invfentory/productservice-gw/v1.0

order:
  service:
    url: https://orderservice-337812374841.us-central1.run.app

supplier:
  service:
    url: https://d201c53c-c644-4920-ab04-ef977962e680-dev.e1-us-east-azure.choreoapis.dev/invfentory/supplierservice/v1.0

ml:
  service:
    url: https://supplier-model.onrender.com

inventory:
  service:
    url: http://localhost:8085

resource:
  service:
    url: https://d201c53c-c644-4920-ab04-ef977962e680-dev.e1-us-east-azure.choreoapis.dev/invfentory/resourseservice/v1.0

# Logging
logging:
  level:
    com.ApiGateway.ApiGateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
