server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

# JWT Configuration (SAME SECRET AS USER SERVICE)
jwt:
  secret: mySecretKeyForJWTTokenGenerationAndValidationThatIsAtLeast512BitsLongToMeetHS512AlgorithmRequirementsForSecureTokenSigning  # Same as your User Service
  expiration: 86400000 # 24 hours

# Service URLs
user:
  service:
    url: http://localhost:8080

product:
  service:
    url: http://localhost:8081

order:
  service:
    url: http://localhost:8082

# Logging
logging:
  level:
    com.ApiGateway.ApiGateway: DEBUG
    org.springframework.cloud.gateway: DEBUG