apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ml-forecast-service
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Allocate more CPU and memory for ML workloads
        run.googleapis.com/cpu: "2"
        run.googleapis.com/memory: "4Gi"
        run.googleapis.com/max-scale: "10"
        run.googleapis.com/min-scale: "0"
        # Increase timeout for ML processing
        run.googleapis.com/timeout: "300s"
    spec:
      containerConcurrency: 10
      containers:
      - image: gcr.io/api-gateway-474511/ml-forecast-service:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: REDIS_URL
          value: "redis://default:gQTgc94xp1OT2hILBizHmNmzI5a8Np3d@redis-18634.c321.us-east-1-2.ec2.redns.redis-cloud.com:18634"
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5